### ISSUE TITLE
metrics.turtles only works for turtle-own but not for <breed>-own

### ISSUE THREAD

**Issue by nldoc** [ropensci/nlrx#12] opened 2018-12-19 13:46 UTC
-own variables can be either defined for all turtles (turtles-own) or specific breeds (e.g. sheep-own). Currently the metrics.turtles measurement slot only works with turtles-owns variables.

The quickfix would be to copy-paste all breed-own variables to the turtles-own variables.
However, it would be nice if nlrx would work with these breed-own variables as well.

**Comment by marcosci** [comment] 2019-01-10 00:31
This would mean that the breeds would need to be specified in util_gather, or?

Meaning if one would use metrics.turtles with breed-own variables one would have to pass that to the function, or? Otherwise, we wouldn't be capable to distinguish that?

**Comment by nldoc** [comment] 2019-01-10 09:11
Yes, we would need the additional breed information for each variable within metrics.turtle/metrics.links. My preferred solution would be to have a list instead of a vector. Each item of the list is named by a breed and contains a vector with the breed variables to measure:
`metrics.turtles = list("turtles" = c("who", "pxcor", "pycor"), "sheep" = c("sheep-var1", sheep-var2"), "wolves" = c("wolves-var1", "wolves-var2"))`
Then, in the xml file we define a reporter for each breed that is measured. Getting get_nl_spatial to work with a variable number of metrics.turtles could be tricky but should be possible.

**Comment by marcosci** [comment] 2019-02-20 18:21
This should be fixed now, or?

**Comment by mrsensible** [comment] 2019-02-28 22:14
Unfortunately, this still returns an error message: `Error in validObject(.Object) : 
  invalid class “experiment” object: invalid object for slot "metrics.turtles" in class "experiment": got class "list", should be or extend class "character"`.

**Comment by marcosci** [comment] 2019-03-03 21:18
Can you provide a reproducible example for that? This should actually been fixed since a couple of days, are you sure that you updated nlrx? Thanks!

**Comment by mrsensible** [comment] 2019-03-03 21:37
Yes I am using **nlrx version 0.1.0**.
Here is the code chunck of your Fire model (https://ropensci.github.io/nlrx/articles/articles/interfacing-different-models.html).
```r
## Step1: Create a nl obejct:
nl <- nl(nlversion = "6.0.4",
         nlpath = netlogopath,
         modelpath = file.path(netlogopath, "app/models/Sample Models/Earth Science/Fire.nlogo"),
         jvmmem = 1024)

## Step2: Add Experiment
nl@experiment <- experiment(expname = "fire",
                            outpath = outpath,
                            repetition = 1,    
                            tickmetrics = "true",
                            idsetup = "setup", 
                            idgo = "go",       
                            runtime = 500,
                            evalticks = seq(1,500),
                            metrics = c("count patches"),
                            metrics.turtles = list("turtles" = c("who", "pxcor", "pycor", "breed", "color")),
                            metrics.patches = c("pxcor", "pycor", "pcolor"),
                            constants = list('density' = 62)
)
```
Having run on my MacOSX, it returns a result as `Error in validObject(.Object) : 
  invalid class “experiment” object: invalid object for slot "metrics.turtles" in class "experiment": got class "list", should be or extend class "character"`.


Instead of assigning `turtles` in the `metrics.turtles`, I coded it without assigning <breeds>-own to as an agentset, which seem to work fine.
```r
## Step1: Create a nl obejct:
nl <- nl(nlversion = "6.0.4",
         nlpath = netlogopath,
         modelpath = file.path("D:/github/jasss/Gangnam_v6.nlogo"),
         #modelpath = file.path("/Users/yun-ile/github/jasss/Gangnam_v6.nlogo"),
         jvmmem = 1024)

## Step2: Add Experiment
nl@experiment <- experiment(expname = "seoul",
                            outpath = outpath,
                            repetition = 1,   
                            tickmetrics = "true",
                            idsetup = "setup",  
                            idgo = "go",        
                            runtime = 8764,
                            evalticks=seq(1,8764),
                            constants = list("PM10-parameters" = 100,
                                             "AC" = 100
                                             ),
                            metrics.turtles =  c("xcor", "ycor", "color", "heading", "who", 
                                                 "homename", "destinationName", "age", "health"),
                            metrics.patches = c("pxcor", "pycor", "pcolor", "ts__kal"))

```

**Comment by nldoc** [comment] 2019-03-03 22:11
On my system the first code snippet runs fine, however I am on Windows, so it could still be an issue related to OSX. We introduced the named list feature for metrics.turtles only some days ago. Your second example, where you define metrics.turtles as a vector of strings, is our old syntax. Thus, it is most likely that you are running an older version of the nlrx package where the named list feature was not yet supported.
We just discovered, that the installation command snippet in our readme vignette might not be pointing to the current version of nlrx.  Could you please reinstall nlrx using the following command and report if you still get an error for your first code snippet? Thx.
`devtools::install_github("ropensci/nlrx")`

**Comment by mrsensible** [comment] 2019-03-03 22:50
Hi there,
After downloading your recent update, it works fine! Many thanks for your response.

**Closed** 2019-03-04 00:08 UTC
