### ISSUE TITLE
Parallelisation fails under the implicit futures operator

### ISSUE THREAD

**Issue by ltdroy** [ropensci/nlrx#30] opened 2019-09-26 08:56 UTC
## Issue

The issue is that (at least under some conditions) parallelisation fails when using the implicit futures operator (%<-%). However, parallelisation succeeds when using a normal assignment operator with the `future` library and a multisession plan. 

## Code producing the issue (R 3.5.3, nlrx 0.2.0, Windows 10)

```
nl@experiment <- experiment(
  expname = "wolf-sheep",
  outpath = outpath,
  repetition = 1,
  tickmetrics = "false",
  idsetup = "setup",
  idgo = "go",
  runtime=10,
#  evalticks=seq(40,50),
  metrics=c("count sheep", "count wolves", "count patches with [pcolor = green]"),
  metrics.turtles=list("turtles"= c("energy")),
  variables = list(
    "initial-number-sheep" = list(min=50, max=150, qfun="qunif"),
    "initial-number-wolves" = list(min=50, max=150, qfun="qunif")),
  constants = list(
    "model-version" = "\"sheep-wolves-grass\"",
    "grass-regrowth-time" = 30,
    "sheep-gain-from-food" = 4,
    "wolf-gain-from-food" = 20,
    "sheep-reproduce" = 4,
    "wolf-reproduce" = 5,
    "show-energy?" = "false"))

nl@simdesign <- simdesign_lhs(
  nl=nl,
  samples=20,
  nseed=1,
  precision=3
)

library(future)

plan(multisession)

results  %<-%  run_nl_all(nl = nl, split = 5)

results.df <- results
```
## Reason to suspect that parallelisation fails

The simulation runs slowly and inspection of (windows) system processes shows multiple R background processes but only 1 JVM instance (see attached screenshot). 

![Example Screenshot](https://user-images.githubusercontent.com/33451208/65673569-eff84780-e042-11e9-9391-3e3cf77cd9fa.png)

## Workaround 

If, instead of...

```
library(future)

plan(multisession)

results  %<-%  run_nl_all(nl = nl, split = 5)

results.df <- results
```
...the following is used (note that the implicit futures operator is not used)...
```
library(future)

plan(multisession)

results.df <- run_nl_all(nl = nl, split = 5)
```
... then parallelisation succeeds and is visible as the initialisation of 5 JVM processes. The speed with which the set of simulated runs are executed improves accordingly.

**Comment by nldoc** [comment] 2019-09-26 09:14
Thank you very much for pointing out this issue. I can reproduce this issue on my system.
However, to me it is not clear if this is caused by an issue in the furrr package, the future package or if it is our fault.
It seems like the outer loop distributes the parameter chunks to the R processes successfully, but fails to distribute the single model runs to individual JVMs.
We will do some more research to check if we find a solution to run implicit futures in parallel as well.

For the moment we suggest to not use implicit futures for run_nl_all(). 
We updated the corresponding section in the advanced configuration vignette and the documentation of run_nl_all().

**Comment by nldoc** [comment] 2019-09-27 06:54
I found a solution to this problem.
The `run_nl_all()` function uses a nested `furrr::future_map_dfr()` function in order to parallelize the simulations. While the outer loop creates the workers for handling random-seeds/split chunks, the inner loop then loops over the actual simulations (siminputrows). The future package seems to recognize this as a nested future, which are handled differently for explicit and implicit futures (see https://github.com/HenrikBengtsson/future#implicit-or-explicit-futures). For nested futures, one can actually define the plan for parallelization on each nesting level separately. However, by default the parallelization is done on the outer level, but not on the inner level (`plan(list(multiprocess, sequential))`). In our case however this does not work as we are mainly interest in parallelizing the actual simulations. Defining the future plan as `plan(list(sequential, multiprocess))` actually did the job for me. 
Ideally, when sending jobs to a remote cluster one can parallelize on both levels. In such a case, the outer level would be distributed to seperate cluster nodes, whereas the cluster nodes itself distribute parallel simulations to the cores of the node.

Could you please check if this solution works for you as well?
We will then update our manual accordingly.

**Comment by ltdroy** [comment] 2019-09-30 10:31
Hi @nldoc, thanks very much for looking into this so quickly. This solution seems to work for me as-well. Just a slight caveat: I did have some issues with a large scale simulation not finishing (2 JVM processes out of 6 just keep running forever without resolving) using this method. But that's probably just a problem with the Netlogo model rather than nlrx.

**Comment by nldoc** [comment] 2019-09-30 11:18
Great, I will close this issue then. 
However, I still might look into the problem of not resolving JVMs again. Do you refer to the same example as printed above or did this happen with your own model?
Cheers,
nldoc

**Closed by nldoc** 2019-09-30 11:18 UTC

**Comment by ltdroy** [comment] 2019-10-10 09:08
Hi @nldoc,

That was with my own model.

Thanks,
ltdroy
